(ede-cpp-root-project "mp3_stm32"
                      :name "mp3_stm32"
      		      :compile-command "make"
                      :file "/home/lyra/b/mp3_stm32/project.el"
                      :include-path '("/helix_fixpt/real"
                                      "/helix_fixpt/pub"
                                      "/Middlewares/Third_Party/FatFs/src"
                                      "/Middlewares/Third_Party/FatFs/src/drivers"
                                      "/Drivers/CMSIS/Device/ST/STM32F4xx/Include"
                                      "/Drivers/CMSIS/Include"
                                      "/Drivers/STM32F4xx_HAL_Driver/Inc"
                                      "/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy"
                                      "/Flac"
                                      "/Inc"
                                      "/Src"
                                      )
		      )